version: '3.3'

services:
  ztg-snapshot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ENDPOINT_URL: ${ENDPOINT_URL}
    secrets:
      - credentials

secrets:
  credentials:
    external: true
