version: '3.3'

services:
  ztg-snapshot:
    build:
      context: .
      dockerfile: Dockerfile
      ports:
      - "127.0.0.1:5000:5000"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      ENDPOINT_URL: ${ENDPOINT_URL}
    
    # volumes:
    # - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
  
# secrets:
#   credentials:
#     external: true
